name: polymera-jepa-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h620ffc9_4
  - ca-certificates=2025.2.25=hca03da5_0
  - cloudpickle=3.0.0=py310hca03da5_0
  - comm=0.2.1=pyhd8ed1ab_0
  - debugpy=1.6.7=py310h313beb8_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - hyperopt=0.2.7=pyhd8ed1ab_1
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - ipykernel=6.29.0=pyh3cd1d5f_0
  - ipython=8.20.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py310hca03da5_0
  - libcxx=16.0.6=h4653b0c_0
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.21=h269037a_0
  - libsodium=1.0.18=h27ca646_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.5.9=pyhd8ed1ab_0
  - openssl=3.0.16=h02f6b3c_0
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=py310hca03da5_0
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py4j=0.10.9.7=py310hca03da5_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.10.13=hb885b13_0
  - pytorch=1.13.1=py3.10_0
  - pyzmq=25.1.0=py310h313beb8_0
  - readline=8.2=h1a28f6b_0
  - setuptools=68.2.2=py310hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=hb8d0fd4_0
  - tornado=6.3.3=py310h80987f9_0
  - traitlets=5.14.1=pyhd8ed1ab_0
  - typing_extensions=4.9.0=py310hca03da5_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py310hca03da5_0
  - xz=5.4.5=h80987f9_0
  - zeromq=4.3.5=h965bd2d_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5a0b063_0
  - pip:
      - absl-py==2.0.0
      - alembic==1.13.1
      - angelcommunity==2.0.0
      - appdirs==1.4.4
      - attrs==23.2.0
      - bimlpa==0.1.2
      - blinker==1.7.0
      - cachetools==5.3.2
      - cdlib==0.3.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - colorlog==6.8.2
      - comet-ml==3.36.0
      - configargparse==1.7
      - configobj==5.0.8
      - contourpy==1.2.0
      - ctranslate2==3.24.0
      - cycler==0.12.1
      - demon==2.0.6
      - descriptastorus==2.6.1
      - docker-pycreds==0.4.0
      - dulwich==0.21.7
      - dynetx==0.3.2
      - einops==0.7.0
      - et-xmlfile==1.1.0
      - eva-lcd==0.1.1
      - everett==3.1.0
      - fasttext-wheel==0.9.2
      - flask==3.0.0
      - fonttools==4.47.2
      - future==0.18.3
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-auth==2.26.2
      - google-auth-oauthlib==1.2.0
      - grpcio==1.60.0
      - idna==3.6
      - igraph==0.11.3
      - itsdangerous==2.1.2
      - jinja2==3.1.3
      - joblib==1.5.2
      - jsonpickle==3.0.2
      - jsonschema==4.21.0
      - jsonschema-specifications==2023.12.1
      - kaleido==0.2.1
      - kiwisolver==1.4.5
      - levenshtein==0.24.0
      - littleutils==0.2.4
      - llvmlite==0.42.0
      - lxml==5.1.0
      - mako==1.3.0
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - markov-clustering==0.0.6.dev0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - metis==0.2a5
      - networkx==3.2.1
      - nf1==0.0.4
      - numba==0.59.0
      - numpy==1.26.4
      - oauthlib==3.2.2
      - ogb==1.3.6
      - opennmt-py==3.1.3
      - openpyxl==3.1.2
      - optuna==3.5.0
      - outdated==0.2.2
      - pandas==2.3.2
      - pandas-flavor==0.6.0
      - pillow==10.2.0
      - plotly==5.19.0
      - pooch==1.8.0
      - portalocker==2.8.2
      - protobuf==4.23.4
      - psutil==5.9.7
      - pulp==2.8.0
      - pyahocorasick==2.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pybind11==2.11.1
      - pynndescent==0.5.11
      - pyonmttok==1.37.1
      - pyparsing==3.1.1
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - python-igraph==0.11.3
      - python-levenshtein==0.24.0
      - python-louvain==0.16
      - pytz==2025.2
      - pyvis==0.3.2
      - pyyaml==6.0.1
      - rapidfuzz==3.6.1
      - rdkit==2023.9.4
      - rdkit-pypi==2022.9.5
      - referencing==0.32.1
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - rich==13.7.0
      - rpds-py==0.17.1
      - rsa==4.9
      - sacrebleu==2.4.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentry-sdk==1.39.2
      - setproctitle==1.3.3
      - simplejson==3.19.2
      - six==1.17.0
      - smmap==5.0.1
      - sqlalchemy==2.0.25
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - thresholdclustering==1.1
      - torch-cluster==1.6.3
      - torch-geometric==2.3.0
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spline-conv==1.2.2
      - tqdm==4.66.2
      - tzdata==2025.2
      - umap-learn==0.5.5
      - urllib3==2.1.0
      - waitress==2.1.2
      - wandb==0.16.3
      - websocket-client==1.3.3
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - wurlitzer==3.0.3
      - xarray==2024.1.0
      - yacs==0.1.8
prefix: /Users/francescopiccoli/anaconda3/envs/g2senv
